version: "3.3"
services:
  binotify-app-web:
    build:
      context: ./binotify-app
      dockerfile: Dockerfile
    image: binotify-app-web:latest
    volumes:
      - ./binotify-app/src:/var/www/html
    ports:
      - ${BINOTIFY_APP_WEB_PORT:-8008}:80

  binotify-app-db:
    image: postgres:latest
    restart: always
    ports:
      - ${BINOTIFY_APP_DB_PORT:-15432}:5432
    environment:
      - POSTGRES_PASSWORD=${BINOTIFY_APP_DB_PASSWORD:-postgres}
      - POSTGRES_DB=${BINOTIFY_APP_DB_NAME:-database}
    volumes:
      - ./binotify-app/database.sql:/docker-entrypoint-initdb.d/database.sql

  binotify-rest-service-app:
    build:
      context: ./binotify-rest-service
      dockerfile: Dockerfile
    image: binotify-rest-service-app:latest
    volumes:
      - ./binotify-rest-service/src:/usr/src/app/src
    ports:
      - ${BINOTIFY_REST_SERVICE_APP_PORT:-8080}:${BINOTIFY_REST_SERVICE_APP_PORT:-8080}
    depends_on:
      binotify-rest-service-db:
        condition: service_healthy

  binotify-rest-service-db:
    image: mysql:latest
    restart: always
    ports:
      - ${BINOTIFY_REST_SERVICE_DB_PORT:-13306}:3306
    environment:
      MYSQL_DATABASE: "${BINOTIFY_REST_SERVICE_DB_NAME:-database}"
      MYSQL_USER: "${BINOTIFY_REST_SERVICE_DB_USER:-user}"
      MYSQL_PASSWORD: "${BINOTIFY_REST_SERVICE_DB_PASSWORD:-password}"
      MYSQL_ROOT_PASSWORD: "${BINOTIFY_REST_SERVICE_DB_ROOT_PASSWORD:-password}"
    volumes:
      - ./binotify-rest-service/database.sql:/docker-entrypoint-initdb.d/database.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 30s
